from fastapi import APIRouter, HTTPException, status, Request
from app.schemas.resume_schema import ResumeInput, ResumeOutput
from app.services.resume_service import ResumeService
from app.core.limiter import limiter
from app.core.config import settings

router = APIRouter(prefix="/api/v1", tags=["Resume Builder"])

_service = ResumeService()


@router.post(
    "/generate-resume",
    response_model=ResumeOutput,
    status_code=status.HTTP_200_OK,
    summary="Generate an ATS-friendly resume",
    description=(
        "Accepts structured candidate data and returns a fully formatted, "
        "ATS-optimized resume in plain text generated by the Groq LLM via LangChain."
    ),
)
@limiter.limit(settings.RATE_LIMIT_GENERATION)
async def generate_resume(request: Request, payload: ResumeInput) -> ResumeOutput:
    try:
        return _service.generate_resume(payload)
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Resume generation failed: {str(exc)}",
        )
